### ISSUE TITLE
Address the requirements from OSU

### ISSUE THREAD

**Issue by ZihengSun** [CSISS/cc#43]
Statistics
    Point
        In Box, "Clicked Lat/Lon" need to rename, Probably just "X" and "Y"
        Can the box list vertically? or drag to change box size? - will do it without scrolling
        Box title is repeated in "Layer name", no need? - remove
        Box title font is too big. - fix this one by adding extra process
        ASR (example) in North Pole project, the Lat/Lon information on top is wrong. - probably projection issue
        
    Linestring
        Sometime only works on right window. Left window is often not working at all.  - the plot is loading and users should be aware of the situation, 3-D field, to adjust the color range/pilot within the visible range. Get the maximum and minimum on the line string to get a color plot normalized.
        Cloase draw points mode, sometime, need to be done twice. - correct it

**Comment by ZihengSun** [comment]
In Box, "Clicked Lat/Lon" need to rename, Probably just "X" and "Y" - solved by @scvetojevic1402 
Can the box list vertically? or drag to change box size? - will do it without scrolling - fixed by @scvetojevic1402 
Box title is repeated in "Layer name", no need? - remove - fixed by @scvetojevic1402 
Box title font is too big. - fix this one by adding extra process - fixed by @scvetojevic1402 
ASR (example) in North Pole project, the Lat/Lon information on top is wrong. - probably projection issue

**Comment by ZihengSun** [comment]
@scvetojevic1402 is the last problem (ASR projection problem) solved?

**Comment by scvetojevic1402** [comment]
Not yet.

**Comment by ZihengSun** [comment]
![image](https://user-images.githubusercontent.com/17322987/68616457-10654f80-0493-11ea-8bab-55fd6afb845f.png)
Fixed.
